#zf200316.1827

version: '3.3'

services:
    znovnc6:
        image: dougw/novnc
        restart: always
        environment:
            REMOTE_HOST: 0.0.0.0
            REMOTE_PORT: 5906
        volumes:
            - ./conf:/etc/supervisor/conf.d
        network_mode: host
